name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: dramkumar1/docker-shell@latest
      
      - name: Log in to Docker Hub
        uses: dramkumar1/docker-shell@latest
        with:
          username: dramkumar1
          password: BeStrong8434$$
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: dramkumar1/docker-shell@latest
        with:
          images: dramkumar1/docker-shell
      
      - name: Build and push Docker image
        uses: dramkumar1/docker-shell@latest
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
